### ISSUE TITLE
Restrict what users can see based on user office permissions

### ISSUE THREAD

**Issue by ElliotAOram** [autoreduction/queue-processor#395] opened 2019-10-10 16:11 UTC
Issue raised by: [user]

### What?
Currently any user can see ALL reduction jobs etc. in the web application. We nee to constrain this so that users can only see the instruments / experiments that they are associated with. 

As part of this we need to create some test accounts for the web app that have specific sets of permissions

### Where?
WebApp authentication? Not sure where to start with this one , will require some digging as to where we can get the auth values from the user office

### How to test the issue is resolved
* Log in with newly created test user accounts. 
* Ensure that these users have the correct permissions and can ONLY view the instruments / runs they are associated with.

It may be valuable to get this validated by instrument scientists as well to make sure.

**Comment by dtasev** [comment] 2021-02-09 11:14
Dupe of #927

**Closed** 2022-08-17 13:22 UTC
Labels: ❗️ Bug
